import "@/styles/globals.css";

import { Inter as FontSans } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";

import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <TRPCReactProvider>
            <MaxWidthWrapper className="min-h-[calc(100vh-200px)]">
              <NavBar />
              {children}
              <Toaster />
            </MaxWidthWrapper>
            <Footer />
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
